"""Add LLM verification fields

Revision ID: 94aefe6054c1
Revises: b72c3ee7d731
Create Date: 2026-08-31 02:22:44.255185

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94aefe6054c1'
down_revision: str | Sequence[str] | None = 'b72c3ee7d731'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_results', sa.Column('llm_verification_status', sa.String(), nullable=True))
    op.add_column('compliance_results', sa.Column('llm_verification_message', sa.Text(), nullable=True))
    op.add_column('compliance_results', sa.Column('llm_verification_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extracted_products', sa.Column('original_nlp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_products', 'original_nlp_data')
    op.drop_column('compliance_results', 'llm_verification_references')
    op.drop_column('compliance_results', 'llm_verification_message')
    op.drop_column('compliance_results', 'llm_verification_status')
    # ### end Alembic commands ###
