"""Add full compliance engine fields

Revision ID: b72c3ee7d731
Revises: b8a850f46936
Create Date: 2026-08-31 01:52:01.366563

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b72c3ee7d731'
down_revision: str | Sequence[str] | None = 'b8a850f46936'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_results', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('compliance_results', sa.Column('as_on_date', sa.String(), nullable=True))
    op.add_column('compliance_results', sa.Column('total_penalty_exposure_inr', sa.Float(), nullable=True))
    op.add_column('compliance_results', sa.Column('needs_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('compliance_results', sa.Column('exempted', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_results', 'exempted')
    op.drop_column('compliance_results', 'needs_review')
    op.drop_column('compliance_results', 'total_penalty_exposure_inr')
    op.drop_column('compliance_results', 'as_on_date')
    op.drop_column('compliance_results', 'score')
    # ### end Alembic commands ###
